# Generated by Django 4.0.3 on 2022-07-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_description',
            new_name='product_description',
        ),
    ]
